"""lastupdate in inet_ether and users

Revision ID: 37ff8c29183d
Revises: 4d58a25d196b
Create Date: 2015-12-28 15:21:10.288603

"""

# revision identifiers, used by Alembic.
revision = '37ff8c29183d'
down_revision = '4d58a25d196b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inet_ether', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('inet_ether', sa.Column('lastupdate', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'inet_ether', ['mac'])
    op.add_column('users', sa.Column('crdate', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('lastupdate', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastupdate')
    op.drop_column('users', 'crdate')
    op.drop_constraint(None, 'inet_ether')
    op.drop_column('inet_ether', 'lastupdate')
    op.drop_column('inet_ether', 'is_active')
    ### end Alembic commands ###
