"""Add first tables

Revision ID: 4d58a25d196b
Revises: 121482e6f837
Create Date: 2015-12-27 20:08:17.082959

"""

# revision identifiers, used by Alembic.
revision = '4d58a25d196b'
down_revision = '121482e6f837'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inet_ether',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=32), nullable=False),
    sa.Column('ip', sa.String(length=32), nullable=True),
    sa.Column('access_type', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=32), nullable=True),
    sa.Column('passwd', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('inet_ether')
    ### end Alembic commands ###
