"""empty message

Revision ID: dc07d6d6d540
Revises: 37ff8c29183d
Create Date: 2003-01-17 12:10:18.812488

"""

# revision identifiers, used by Alembic.
revision = 'dc07d6d6d540'
down_revision = '37ff8c29183d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arp_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=32), nullable=False),
    sa.Column('ip', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arp_cache')
    ### end Alembic commands ###
